SocialGouv/reva

- components/Survey.vue
- components/UserForm.vue
> feat: explain next steps to candidates at the end of the survey

- api/candidate/data.ts
- cypress.json
- cypress/fixtures/candidates.json
- cypress/fixtures/example.json
- cypress/integration/backoffice/front/candidates.spec.js
- cypress/plugins/index.js
- cypress/support/commands.js
- cypress/support/index.js
- elm_app/src/Main.elm
- elm_app/src/Page/Candidates.elm
- elm_app/src/View/Helpers.elm
- package.json
- yarn.lock
- Close https://github.com/SocialGouv/reva/issues/85
- Add Cypress tests
- Add candidates stub and fixtures to run front-only tests (without the API)
⚠️ Cypress tests are not run on the CI (we need to properly setup the baseUrl with the container address).
> feat: show all survey dates

- api/candidate/data.ts
- cypress/integration/backoffice/front/candidates.spec.js
- elm_app/src/Main.elm
- elm_app/src/Page/Candidates.elm
- elm_app/src/Page/Login.elm
- elm_app/src/View.elm
- elm_app/src/View/Icons.elm
- elm_app/src/View/Timeline.elm
> feat: add timeline of survey dates and pending event

- api/auth/index.ts
- api/candidate/data.ts
- api/candidate/index.ts
The code is a bit ugly (lot of any, too much if) but it does the job
> feat: add endpoint to list all candidates answers

- .github/workflows/ci.yml
- components/Footer.vue
Close https://github.com/SocialGouv/reva/issues/98
"Accessibilité : non conforme", linked to https://beta.gouv.fr/accessibilite/
> feat: add accessibility footer link

- elm_app/src/View/Candidate.elm
> fix: fix the order of pending statuses, remove the safe integer

- cypress/integration/backoffice/front/candidates.spec.js
- elm_app/src/Main.elm
- elm_app/src/Page/Candidates.elm
- elm_app/src/View/Candidate.elm
- elm_app/src/View/Candidate/Recognition.elm
- elm_app/src/View/Icons.elm
Close https://github.com/SocialGouv/reva/issues/120
> feat: add recognition selection and contextualization steps

- cypress/integration/backoffice/front/candidates.spec.js
- elm_app/src/Page/Candidates.elm
- elm_app/src/Page/Candidates/Recognition.elm
Close https://github.com/SocialGouv/reva/issues/149
> feat: create skill from footer and update labels

- elm_app/src/Page/Candidates/Recognition.elm
> feat: describe recognition module on first screen

- packages/reva-website/content/PolitiqueDeConfidentialite.md
- packages/reva-website/elm.json
- packages/reva-website/src/Page/PolitiqueDeConfidentialite.elm
- packages/reva-website/src/View/Markdown.elm
Close https://github.com/SocialGouv/reva/issues/191
> feat(privacy): add privacy page

- package-lock.json
- packages/reva-app/package.json
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Button/index.tsx
- packages/reva-app/src/components/atoms/TextResult/index.tsx
- packages/reva-app/src/components/organisms/Card/Card.stories.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/components/organisms/Card/view.tsx
- packages/reva-app/src/components/organisms/Results/index.tsx
Related https://github.com/SocialGouv/reva/issues/201
> feat(app): add fullscreen certificate view with transition from closed ones

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/TextResult/index.tsx
- packages/reva-app/src/components/organisms/Card/Card.stories.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/components/organisms/Results/Results.stories.tsx
Related to https://github.com/SocialGouv/reva/issues/202
> feat(app): add job certificates page

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/TextResult/index.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
> feat(app): add certificates fixtures and handle long titles

- packages/reva-app/src/components/atoms/Icons/index.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
> feat(app): add plus icon to card

- packages/reva-app/src/components/atoms/Icons/index.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/index.css
Related https://github.com/SocialGouv/reva/issues/201
> feat(app): add back icon

- packages/reva-app/src/components/atoms/LoremIpsum/index.jsx
- packages/reva-app/src/components/atoms/TextResult/index.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/fixtures/certificates.ts
Certification details are scrollable, decorative img is below text:
> feat(app): support long certificate descriptions and small devices

- package-lock.json
- packages/reva-app/package.json
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Header/Header.stories.tsx
- packages/reva-app/src/components/atoms/Header/index.tsx
- packages/reva-app/src/components/atoms/Icons/index.tsx
- packages/reva-app/src/components/atoms/TextResult/index.tsx
- packages/reva-app/src/components/molecules/BackButton/index.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/components/organisms/Results/Results.stories.tsx
- packages/reva-app/src/config.ts
- packages/reva-app/src/interface.ts
- packages/reva-app/tailwind.config.js
Related https://github.com/SocialGouv/reva/issues/214
Add page with next / previous transition
> feat(app): add candidate submission loading page

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Button/index.tsx
- packages/reva-app/src/components/atoms/Checkbox/Checkbox.stories.tsx
- packages/reva-app/src/components/atoms/Checkbox/index.tsx
- packages/reva-app/src/components/atoms/Title/Title.stories.tsx
- packages/reva-app/src/components/atoms/Title/index.tsx
- packages/reva-app/src/components/organisms/Page/index.tsx
- packages/reva-app/src/config.ts
- packages/reva-app/src/pages/CertificateDetails.tsx
- packages/reva-app/src/pages/Certificates.tsx
- packages/reva-app/src/pages/ProjectGoals.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
Related https://github.com/SocialGouv/reva/issues/217
> feat(app): add goals page

- packages/reva-app/src/components/organisms/Page/index.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
Related https://github.com/SocialGouv/reva/issues/214
> feat(app): add project progress bar

- packages/reva-app/ios/App/App/capacitor.config.json
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/pages/CertificateDetails.tsx
- packages/reva-app/src/pages/Certificates.tsx
- packages/reva-app/src/utils/useWindowListener.tsx
- packages/reva-app/src/utils/useWindowSize.tsx
On mobile we now properly handle the address / status bars and screen height. 
On desktop :
> feat(app): support mobile and desktop browsers

- packages/reva-app/ios/App/App/capacitor.config.json
- packages/reva-app/src/components/atoms/Checkbox/index.tsx
- packages/reva-app/src/interface.ts
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectGoals.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
- packages/reva-app/src/utils/projectProgress.tsx
Related https://github.com/SocialGouv/reva/issues/214
> feat(app): add goals edition and project progress

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Button/index.tsx
- packages/reva-app/src/components/atoms/Input/Input.stories.tsx
- packages/reva-app/src/components/atoms/Input/index.tsx
- packages/reva-app/src/index.css
- packages/reva-app/src/pages/ProjectExperiences.tsx
- packages/reva-app/src/pages/ProjectGoals.tsx
Related https://github.com/SocialGouv/reva/issues/230
> feat(app): add experience title and date

- packages/reva-app/src/components/atoms/Input/index.tsx
- packages/reva-app/src/components/atoms/Select/Select.stories.tsx
- packages/reva-app/src/components/atoms/Select/index.tsx
- packages/reva-app/src/components/atoms/Textarea/Textarea.stories.tsx
- packages/reva-app/src/components/atoms/Textarea/index.tsx
- packages/reva-app/src/pages/ProjectExperiences.tsx
Related https://github.com/SocialGouv/reva/issues/230
> feat(app): add experience description and duration

- packages/reva-app/ios/App/App/Info.plist
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Button/index.tsx
- packages/reva-app/src/components/atoms/Input/index.tsx
- packages/reva-app/src/components/atoms/Select/index.tsx
- packages/reva-app/src/pages/ProjectExperience.tsx
> feat(app): add experience form validation

- packages/reva-app/src/App.tsx
- packages/reva-app/src/interface.ts
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectExperience.tsx
- packages/reva-app/src/pages/ProjectExperiences.tsx
- packages/reva-app/src/pages/ProjectGoals.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
Related https://github.com/SocialGouv/reva/issues/230
> feat(add): add page to display all experiences

- packages/reva-app/src/components/atoms/Icons/index.tsx
- packages/reva-app/src/components/atoms/Input/index.tsx
- packages/reva-app/src/components/atoms/Select/index.tsx
- packages/reva-app/src/components/molecules/BackButton/index.tsx
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectExperience.tsx
- packages/reva-app/src/pages/ProjectExperiences.tsx
Related https://github.com/SocialGouv/reva/issues/230
> feat(add): add experience edition and sort experiences by date

- packages/reva-app/src/pages/ProjectExperiences.tsx
- packages/reva-tests/cypress/integration/experiences.spec.js
> feat(app): display experience duration and start date in overview

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/organisms/Card/view.tsx
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectHome.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
Related https://github.com/SocialGouv/reva/issues/292
> feat(app): display a warning message before project submission

- packages/reva-app/ios/App/App/capacitor.config.json
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectHome.tsx
- packages/reva-app/src/pages/ProjectSubmitted.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
- packages/reva-app/src/utils/projectProgress.tsx
- packages/reva-app/tailwind.config.js
Close https://github.com/SocialGouv/reva/issues/292
> feat(app): add project submission pages

- packages/reva-app/src/components/organisms/Card/index.tsx
- packages/reva-app/src/components/organisms/Card/view.tsx
> feat(app): adapt the height of a certification to its content

- package-lock.json
- packages/reva-app/android/app/capacitor.build.gradle
- packages/reva-app/android/app/src/main/assets/capacitor.plugins.json
- packages/reva-app/android/capacitor.settings.gradle
- packages/reva-app/ios/App/Podfile
- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/Button/index.tsx
- packages/reva-app/src/components/organisms/Page/index.tsx
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectHelp.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
- packages/reva-tests/cypress/integration/contact.spec.js
- packages/reva-tests/cypress/integration/experiences.spec.js
- packages/reva-tests/cypress/integration/project.spec.js
> feat(app): add project help page

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/organisms/CandidateButton/index.tsx
- packages/reva-app/src/interface.ts
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/CertificateDetails.tsx
- packages/reva-app/src/pages/Certificates.tsx
- packages/reva-app/src/pages/ProjectContact.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
- packages/reva-app/src/services/candidacyServices.ts
- packages/reva-app/src/utils/projectProgress.tsx
> feat(app): support certification edition

- packages/reva-app/src/machines/main.machine.ts
🚀 🚀 🚀 🚀 🚀 
🎊 🎊 🎊 🎊 🎊 
🕺 🕺 🕺 🕺 🕺
> fix(app): fix navigation glitch on goal page

- packages/reva-app/src/pages/ProjectHelp.tsx
Close https://github.com/SocialGouv/reva/issues/339
> feat(app): improve project help screen

- packages/reva-app/src/components/atoms/Title/index.tsx
- packages/reva-app/src/components/molecules/ProgressTitle/index.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
Close https://github.com/SocialGouv/reva/issues/344
> feat(app): update project submitted page

- packages/reva-admin/graphql/elm/Admin/InputObject.elm
- packages/reva-admin/graphql/elm/Admin/Mutation.elm
- packages/reva-admin/graphql/elm/Admin/Object/Candidacy.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidacyStatus.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidacySummary.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidateGoal.elm
- packages/reva-admin/graphql/elm/Admin/Object/Certification.elm
- packages/reva-admin/graphql/elm/Admin/Object/Companion.elm
- packages/reva-admin/graphql/elm/Admin/Object/Experience.elm
- packages/reva-admin/graphql/elm/Admin/Object/Goal.elm
- packages/reva-admin/graphql/elm/Admin/Object/Profession.elm
- packages/reva-admin/graphql/elm/Admin/Object/Referential.elm
- packages/reva-admin/graphql/elm/Admin/Object/SearchCertificationsAndProfessionsResult.elm
- packages/reva-admin/graphql/elm/Admin/Query.elm
- packages/reva-admin/graphql/elm/Admin/VerifyScalarCodecs.elm
- packages/reva-admin/package.json
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Scalar.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Request.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Date.elm
- packages/reva-api/infra/graphql/candidacy/candidacy.graphql
> feat(admin): display experiences

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
"Autre typologie" is displayed when "Autre" is selected.
> feat(admin): support all form elements for meeeting page

- packages/reva-admin/graphql/elm/Admin/Object/Candidacy.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidacyStatus.elm
- packages/reva-admin/graphql/elm/Admin/Query.elm
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Form/Appointment.elm
- packages/reva-admin/src/Data/Form/Helper.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
TODO:
- save date
- redirect to candidacy after save
> feat(admin): load and save appointment data

- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
If save is a success, redirect to candidacy:
> feat(admin): redirect to candidacy after submitting form

- packages/reva-admin/src/Data/Form/Training.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/src/View/Candidacy.elm
Next step: bind the form to API
> feat(admin): add training form

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
> feat(admin): update form elements to official style

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Steps.elm
> feat(admin): add navigation to training form

- packages/reva-app/src/components/organisms/Card/view.tsx
- packages/reva-app/src/components/organisms/CardSkeleton/index.tsx
- packages/reva-app/src/pages/Certificates.tsx
- packages/reva-app/src/pages/ProjectHome.tsx
- remove jump animation (only use skeleton)
- improve skeleton to better match new card size
> feat(app): improve loading of certifications

- packages/reva-app/src/interface.ts
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectHome.tsx
> feat(app): add organism block in project home

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/organisms/Results/index.tsx
- packages/reva-app/src/pages/Certificates.tsx
> feat(app): improve certification results title and position

- package-lock.json
- packages/reva-app/package.json
- packages/reva-app/src/interface.ts
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/Certificates.tsx
- packages/reva-app/src/pages/ProjectOrganisms.tsx
- packages/reva-app/src/pages/SubmissionHome.tsx
- packages/reva-app/src/services/candidacyServices.ts
> feat(app): add organism selection page and bind selected region

- package-lock.json
- packages/reva-admin/package.json
- packages/reva-admin/src/Data/Form/Appointment.elm
- packages/reva-admin/src/Data/Form/Helper.elm
- packages/reva-admin/src/Data/Form/Training.elm
- packages/reva-admin/src/Data/Referential.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
- add consent checkbox to training form 
- prepare the saving logic for the training form
- support saving based on referentials
> feat(admin): add consent checkbox to training form

- packages/reva-admin/src/Api.elm
- packages/reva-admin/src/Data/Context.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
Goal: add support for token refresh
> chore(admin): refactor context data at top level

- packages/reva-admin/src/KeycloakConfiguration.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/typescript/custom-elements/keycloak.ts
> feat(admin): add header bar with logo and logout link

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Organism.elm
- packages/reva-admin/src/Request.elm
- packages/reva-admin/src/View/Candidacy.elm
> feat(admin): display selected organism

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/View/Steps.elm
> feat(admin): add read-only form view and improve timeline

- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectContact.tsx
- packages/reva-app/src/services/candidacyServices.ts
- packages/reva-tests/cypress/e2e/certificates.cy.js
- packages/reva-tests/cypress/e2e/contact.cy.js
- packages/reva-tests/cypress/e2e/experiences.cy.js
- packages/reva-tests/cypress/e2e/login.cy.js
- packages/reva-tests/cypress/e2e/organism.cy.js
- packages/reva-tests/cypress/e2e/project.cy.js
- packages/reva-tests/cypress/e2e/training-program.cy.js
- packages/reva-tests/cypress/fixtures/candidate1.json
- packages/reva-tests/cypress/fixtures/login-expired.json
- packages/reva-tests/cypress/fixtures/referential.json
> feat(app): redirect to registration form when token is invalid

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
The training form is now validated from the web app.
TODO next: remove consent from API
> feat(admin): remove training consent checkbox

- packages/reva-admin/src/Api.elm
- packages/reva-admin/src/KeycloakConfiguration.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/typescript/custom-elements/keycloak.ts
- add new Api.hasAdminToken, this will very useful in the forthcoming admin-only filters
- is it to hide organism details to non-admins
> feat(admin): hide organism details to non-admin

- packages/reva-admin/graphql/elm/Admin/Object.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidacySummary.elm
- packages/reva-admin/graphql/elm/Admin/Object/CandidateLogged.elm
- packages/reva-admin/graphql/elm/Admin/Query.elm
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Organism.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Request.elm
- packages/reva-admin/src/View/Icons.elm
- packages/reva-api/infra/database/postgres/candidacies.ts
- packages/reva-api/infra/graphql/candidacy/candidacy.graphql
> feat(admin): filter candidacies by organism and display organism name

- packages/reva-admin/graphql/elm/Admin/Object/CandidacySummary.elm
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Request.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Date.elm
- packages/reva-admin/src/View/Icons.elm
- packages/reva-api/infra/database/postgres/candidacies.ts
- packages/reva-api/infra/graphql/candidacy/candidacy.graphql
> feat(admin): display sent date and improve overall design

- packages/reva-admin/src/Data/Referential.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/View/Candidacy.elm
> feat(admin): display department on candidacy

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Page/Candidacies.elm
add candidacy count in each status group:
> feat(admin): add candidacy count in each status group and sort by sent date

- packages/reva-admin/src/Data/Referential.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
> feat(admin): add candidate  degree and vulnerability indicator

- packages/reva-admin/src/Data/Form/Candidate.elm
- packages/reva-admin/src/Data/Form/Helper.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
- packages/reva-api/domain/features/updateCandidate.ts
> feat(admin): enforce requirement on vulnerability indicator and degree

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
> feat(admin): improve form layout with sections and headings

- packages/reva-admin/src/Data/Form/FundingRequest.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
Next steps:
- display certification
- display companions
- display total cost
> feat(admin): add additional funding form elements

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
> feat(admin): display selected certification in funding form

- packages/reva-admin/graphql/elm/Admin/Query.elm
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Organism.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Request.elm
> feat(admin): display the list of companions in funding form

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Page/Candidacies.elm
Quand la candidature est prise en charge : 
Quand le parcours est envoyé par l'architecte : 
Quand le parcours en validé par le candidat :
> feat(admin): display funding request in timeline and review rules

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
> feat(admin): display the total cost of the funding request

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- set link to funding request only if training is validated
- When the funding request is sent and we open the form again it shows the read only version:
> feat(admin): add new funding request and cancel status

- packages/reva-admin/src/Page/Candidacies.elm
⚠️ In the future, we should rename `otherTrainingHourCount` to `totalTrainingHourCount` or similar.
> feat(admin): display the total training hour count

- packages/reva-admin/graphql/elm/Admin/Object/Candidacy.elm
- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Request.elm
- packages/reva-api/infra/database/postgres/candidacies.ts
- packages/reva-api/infra/graphql/candidacy/candidacy.graphql
> feat(admin): can disable some training and set to readonly some elements

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/View.elm
> feat(admin): add funding request main title

- packages/reva-admin/src/Data/Form/FundingRequest.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
> feat(admin): display an error if no companion is selected

- packages/reva-admin/src/Data/Form/Helper.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/View/Heading.elm
> feat(admin): disable fields is not training is checked

- packages/reva-admin/src/Page/Candidacies.elm
> feat(admin): disable certificate fields if no content

- packages/reva-admin/src/Page/Form.elm
> fix(admin): fix overlapping long form terms

- packages/reva-admin/src/Page/Candidacies.elm
PS. we need to refactor this part by making the candidacyId independent from the selected tab, this would simplify the code and make it less error prone.
> fix(admin): fix blank meetings page

- packages/reva-admin/graphql/elm/Admin/Object/FundingRequest.elm
- packages/reva-admin/src/Api/Form/FundingRequest.elm
- packages/reva-admin/src/Data/Form/FundingRequest.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-api/infra/graphql/candidate/candidate.graphql
> feat(admin): display funding request num action if present

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Data/Form/FundingRequest.elm
- packages/reva-admin/src/Page/Candidacies.elm
> feat(admin): add confirmation checkbox on funding request form

- packages/reva-app/src/App.tsx
- packages/reva-app/src/components/atoms/EmailLink/index.tsx
- packages/reva-app/src/index.tsx
- packages/reva-app/src/machines/main.machine.ts
- packages/reva-app/src/pages/ProjectDroppedOut.tsx
- packages/reva-tests/cypress/e2e/dropped-out.cy.js
- packages/reva-tests/cypress/fixtures/candidate2-dropped-out.json
- new page ProjectDroppedOut
- new state / condition
> feat(app): add home page for dropped-out candidates

- packages/reva-api/index.ts
- packages/reva-api/infra/batch/migrateFundingRequestBatches.ts
https://trello.com/c/LphsLKol/275-faire-un-script-de-reprise-des-demandes-de-prise-en-charge-r%C3%A9alis%C3%A9es-avant-lactivation-du-batch-csv
> feat(api): added js migration for missing funding request batches

- package.json
Il like to start the API in a separate terminal for debugging purpose. Don't you?
> chore: Add script to start front apps only (dev mode) <3

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Candidacy/NavigationSteps.elm
> feat(admin): add drop out specific timeline

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/src/View/Candidacy/Filters.elm
- packages/reva-admin/src/View/Candidacy/Tab.elm
> feat(admin): add filter candidacy by status

- packages/reva-api/infra/graphql/index.ts
Comme ça on peut aussi voir les erreurs de formatage
> fix(api): gql error formatter fix

- package-lock.json
- packages/reva-admin/src/Data/Form/DropOut.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Candidacy.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Candidacy/Filters.elm
- packages/reva-admin/src/View/Candidacy/NavigationSteps.elm
- packages/reva-admin/src/View/Candidacy/Tab.elm
- reload candidacies after candidacy updates
- add candidacies skeleton loader:
> feat(admin): reload candidacies after candidacy updates

- .gitignore
- packages/reva-admin/src/Api/Form/PaymentUploads.elm
- packages/reva-admin/src/Data/Form/PaymentRequest.elm
- packages/reva-admin/src/Page/Candidacy.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Page/Form/PaymentRequest.elm
- packages/reva-admin/src/Page/Form/PaymentUploads.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/src/View/Candidacy/Tab.elm
> feat(admin): add 3 steps payment request workflow

- packages/reva-admin/src/Data/Candidacy.elm
- packages/reva-admin/src/View/Candidacy/Filters.elm
- packages/reva-admin/src/View/Candidacy/NavigationSteps.elm
> feat(admin): add payment request in the timeline and filters

- packages/reva-admin/graphql/elm/Admin/InputObject.elm
- packages/reva-admin/graphql/elm/Admin/Mutation.elm
- packages/reva-admin/graphql/elm/Admin/Object/PaymentRequest.elm
- packages/reva-admin/src/Api/Form/PaymentRequest.elm
- packages/reva-admin/src/Data/Form/PaymentRequest.elm
- packages/reva-admin/src/Page/Candidacy.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Page/Form/DropOut.elm
- packages/reva-admin/src/Page/Form/FundingRequest.elm
- packages/reva-admin/src/Page/Form/PaymentRequest.elm
- packages/reva-api/domain/types/candidacy.ts
- packages/reva-api/infra/graphql/finance/features/confirmPaymentRequest.test.ts
- packages/reva-api/infra/graphql/finance/features/confirmPaymentRequest.ts
- packages/reva-api/infra/graphql/finance/features/createOrUpdatePaymentRequestForCandidacy.test.ts
- packages/reva-api/infra/graphql/finance/finance.graphql
- packages/reva-api/prisma/migrations/20230202135645_add_payment_request_invoice_number/migration.sql
- packages/reva-api/prisma/schema.prisma
> feat(admin,api): ask for invoice number in payment request

- packages/reva-admin/src/Api/Form/PaymentUploads.elm
- packages/reva-api/domain/features/addPaymentProof.ts
- packages/reva-api/infra/server/proof-upload.ts
> feat(admin): display payment upload error

- packages/reva-admin/elm.json
- packages/reva-admin/src/KeycloakConfiguration.elm
- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/Page/Candidacy.elm
- packages/reva-admin/src/Page/Form.elm
- packages/reva-admin/src/Page/Loading.elm
- packages/reva-admin/src/Route.elm
- packages/reva-admin/src/View.elm
- packages/reva-admin/src/View/Candidacy.elm
- packages/reva-admin/src/View/Candidacy/Filters.elm
- packages/reva-admin/src/View/Candidacy/NavigationSteps.elm
- packages/reva-admin/src/View/Heading.elm
- packages/reva-admin/src/View/Helpers.elm
- packages/reva-admin/src/View/Icons.elm
- packages/reva-admin/src/View/Navigation.elm
- packages/reva-admin/src/View/Steps.elm
- packages/reva-admin/src/View/Timeline.elm
> chore(admin): migrate from Html.Styled to Html

- packages/reva-admin/src/Main.elm
- packages/reva-admin/src/Page/Subscriptions.elm
> feat(admin): validate or reject subscription request

- packages/reva-api/domain/features/updateCertificationOfCandidacy.ts
- packages/reva-api/infra/database/postgres/candidacies.ts
- packages/reva-api/infra/graphql/candidacy/index.ts
- packages/reva-api/infra/graphql/index.ts
- Update certifcate resets organism : https://trello.com/c/1ztcxHOT/409-supprimer-laap-selectionn%C3%A9-lors-dun-changement-de-certification
- Graphql errors wrapped in HTTP 200 response : https://trello.com/c/sOn0diFj/398-api-graphql-diff%C3%A9rencier-les-erreurs-tech-500-des-erreurs-fonctionnelles
> fix(api): candidacy_updateCeritification also resets organism

- packages/reva-admin/src/Page/Candidacies.elm
- packages/reva-admin/src/View/Candidacy/Filters.elm
> feat(admin): upgrade candidacies page to new design

- package-lock.json
- packages/reva-api/infra/database/postgres/organisms.ts
- packages/reva-api/infra/graphql/subscription/__test__/validateSubscriptionRequest.test.ts
- packages/reva-api/infra/graphql/subscription/domain/validateSubscriptionRequest.ts
- packages/reva-api/infra/graphql/subscription/subscription.resolvers.ts
- packages/reva-api/prisma/data-organisms-certifications-regions.sample.csv
- packages/reva-api/prisma/data-organisms.sample.csv
- packages/reva-api/prisma/migrations/20230524091426_change_organism_unique_constraint/migration.sql
- packages/reva-api/prisma/migrations/20230524130615_add_organism_label_typology_key/migration.sql
- packages/reva-api/prisma/private-seed.ts
- packages/reva-api/prisma/schema.prisma
Trello : "double compte AAP" https://trello.com/c/MhVkVGMi/697-double-compte-aap
> feat(api): Allow multiple organisms with same label / SIRET and different typologies

- packages/reva-admin/graphql/elm/Admin/InputObject.elm
- packages/reva-admin/graphql/elm/Admin/Object/Candidacy.elm
- packages/reva-admin/src/Api/Form/Training.elm
- packages/reva-admin/src/Data/Form/Training.elm
- packages/reva-api/domain/features/submitTrainingForm.ts
- packages/reva-api/infra/database/postgres/candidacies.ts
- packages/reva-api/infra/graphql/candidacy/candidacy.graphql
- packages/reva-api/prisma/migrations/20230627095326_remove_candidacy_validated_by_candidate_field/migration.sql
- packages/reva-api/prisma/schema.prisma
- packages/reva-app/src/interface.ts
- packages/reva-app/src/services/candidacyServices.ts
- packages/reva-tests/cypress/fixtures/candidate1-certification-and-goals-selected.json
- packages/reva-tests/cypress/fixtures/candidate1.json
- packages/reva-tests/cypress/fixtures/candidate2-dropped-out.json
- packages/reva-tests/cypress/fixtures/candidate2-funding-request-sent.json
- packages/reva-tests/cypress/fixtures/candidate2-missing-training-fields.json
- packages/reva-tests/cypress/fixtures/candidate2-submitted.json
- packages/reva-tests/cypress/fixtures/candidate2-taken-over.json
- packages/reva-tests/cypress/fixtures/candidate2-training-confirmed-sent-again.json
- packages/reva-tests/cypress/fixtures/candidate2-training-confirmed.json
- packages/reva-tests/cypress/fixtures/candidate2-training-sent.json
- packages/reva-tests/cypress/fixtures/candidate2.json
- packages/reva-tests/cypress/fixtures/candidate3.json
It's now based on PARCOURS_CONFIRME status
> chore(api): remove unused candidacy validatedByCandidate field

- packages/reva-admin-react/src/app/(aap)/candidacies/[candidacyId]/summary/_components/CandidateExperiencesSectionCard.tsx
- packages/reva-admin-react/src/app/(aap)/candidacies/[candidacyId]/summary/_components/useCandidateSummary.ts
- packages/reva-admin-react/src/app/(aap)/candidacies/[candidacyId]/summary/page.tsx
- packages/reva-admin-react/src/components/card/candidacy-section-card/CandidacySectionCard.tsx
- packages/reva-admin-react/src/components/card/candidacy-section-card/DefaultCandidacySectionCard.tsx
- packages/reva-api/modules/candidacy/candidacy.graphql
- packages/reva-api/modules/dematerialized-feasibility-file/dematerialized-feasibility-file.graphql
Si DF est non dématérialisé : 
Sur le résumé de la candidature :
- On retire le label “À compléter” du bloc “Les informations du candidat”
- Toujours sur le même bloc, on retire le bouton “Compléter”
- On masque la section “Son profil”.
- On masque la section “Sa recevabilité”.
- On ne permet pas l'édition de “Ses expériences”.
> Hide buttons if non demat
